package remas.example.remasfinalproject.data.Dorm;

import androidx.room.Entity;
import androidx.room.PrimaryKey;
import java.io.Serializable;

/**
 * Entity class representing a Dormitory or Apartment listing in the Remas application.
 * This class is mapped to the "dorms" table in the Room database.
 * It implements Serializable to allow passing Dorms objects between Activities via Intents.
 */
@Entity(tableName = "dorms")
public class Dorms implements Serializable {

    /**
     * Unique identifier for each dorm listing. Auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    public long keyId;

    /**
     * The city where the dormitory is located.
     */
    public String city;

    /**
     * The full street address of the dormitory.
     */
    public String address;

    /**
     * The postal code for the dormitory location.
     */
    public String zipcode;

    /**
     * Detailed description of the property, including rules or specific features.
     */
    public String description;

    /**
     * The monthly cost of the dormitory as a String.
     */
    public String rent;

    /**
     * List of features (e.g., Wi-Fi, AC, Laundry) available in the property.
     */
    public String amenities;

    /**
     * URI or path string pointing to the property's image.
     */
    public String photos;

    /**
     * The current availability status (e.g., "Available", "Full", "Under Maintenance").
     */
    public String status;

    /**
     * Default constructor required by the Room persistence library.
     */
    public Dorms() {
    }

    private String DormId; // Alternative ID field for Firebase integration (currently unused)

    /**
     * Returns the unique database key for this listing.
     *
     * @return The primary key ID.
     */
    public long getKeyId() {
        return keyId;
    }

    /**
     * Sets the unique database key for this listing.
     *
     * @param keyId The primary key ID to set.
     */
    public void setKeyId(long keyId) {
        this.keyId = keyId;
    }

    /**
     * Sets the alternative Dorm ID for Firebase integration.
     * Note: This method is currently empty and may be used for future Firebase synchronization.
     *
     * @param key The Dorm ID to set.
     */
    public void setDormId(String key) {
        // TODO: Implement Firebase ID assignment logic
    }

    /**
     * Gets the alternative Dorm ID for Firebase integration.
     *
     * @return The Dorm ID, or null if not set.
     */
    public String getDormId() {
        return DormId;
    }

    /**
     * Gets the city name where the dormitory is located.
     *
     * @return The city name, or null if not set.
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the city name for the dormitory location.
     *
     * @param city The city name to set.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Gets the full street address of the dormitory.
     *
     * @return The property address, or null if not set.
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the full street address for the dormitory.
     *
     * @param address The property address to set.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Gets the postal code for the dormitory location.
     *
     * @return The property zipcode, or null if not set.
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * Sets the postal code for the dormitory location.
     *
     * @param zipcode The property zipcode to set.
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * Gets the detailed description of the property.
     *
     * @return The property description, or null if not set.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the detailed description for the property.
     *
     * @param description The property description to set.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the monthly rent amount for the dormitory.
     *
     * @return The monthly rent value, or null if not set.
     */
    public String getRent() {
        return rent;
    }

    /**
     * Sets the monthly rent amount for the dormitory.
     *
     * @param rent The monthly rent value to set.
     */
    public void setRent(String rent) {
        this.rent = rent;
    }

    /**
     * Gets the list of amenities available in the property.
     *
     * @return The property amenities, or null if not set.
     */
    public String getAmenities() {
        return amenities;
    }

    /**
     * Sets the list of amenities available in the property.
     *
     * @param amenities The property amenities to set.
     */
    public void setAmenities(String amenities) {
        this.amenities = amenities;
    }

    /**
     * Gets the URI or path to the property's images.
     *
     * @return The photos path/URI, or null if not set.
     */
    public String getPhotos() {
        return photos;
    }

    /**
     * Sets the URI or path to the property's images.
     *
     * @param photos The photos path/URI to set.
     */
    public void setPhotos(String photos) {
        this.photos = photos;
    }

    /**
     * Gets the current availability status of the property.
     *
     * @return The property availability status, or null if not set.
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the current availability status of the property.
     *
     * @param status The property availability status to set.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Dorms{" +
                "keyId=" + keyId +
                ", city='" + city + '\'' +
                ", address='" + address + '\'' +
                ", rent='" + rent + '\'' +
                '}';
    }

    /**
     * Adapter Helper: Formats the rent price for display in the RecyclerView list.
     *
     * @return The rent string prefixed with a currency symbol.
     */
    public String getPrice() {
        return rent != null ? "$" + rent : "$0";
    }

    /**
     * Adapter Helper: Provides the city name as the primary title for listing cards.
     *
     * @return The city name or a default placeholder.
     */
    public String getTitle() {
        return city != null ? city : "Unknown Location";
    }

    /**
     * Adapter Helper: Maps amenities data to the 'Beds' display area in the UI layout.
     *
     * @return The amenities string or N/A.
     */
    public String getBeds() {
        return amenities != null ? amenities : "N/A";
    }

    /**
     * Adapter Helper: Returns a static placeholder for bathroom info as this field is not in the DB yet.
     *
     * @return A fixed bathroom count string.
     */
    public String getBaths() {
        return "1 Bath";
    }

    /**
     * Adapter Helper: Returns the property status as the 'Owner' or 'Availability' name.
     *
     * @return The status string or a default placeholder.
     */
    public String getOwnerName() {
        return status != null ? status : "Available";
    }

    /**
     * Inner class representing a simplified Dorm model for Firebase integration.
     * This class contains the same fields as the outer class but is specifically designed
     * for Firebase Realtime Database operations.
     */
    public class Dorm {
        private String DormId; // Unique identifier for the dorm (can be empty initially)
        private String city; // City where the dorm is located
        private String address; // Full street address
        private String zipcode; // Postal code
        private String description; // Detailed property description
        private String rent; // Monthly rent amount
        private String amenities; // Available amenities/features
        private String photos; // Image URI or path
        private String status; // Current availability status

        /**
         * Default constructor required by Firebase for deserialization.
         */
        public Dorm() {
        }

        /**
         * Parameterized constructor to create a new Dorm object with all properties.
         *
         * @param DormId      Unique identifier for the dorm
         * @param city        City location
         * @param address     Full address
         * @param zipcode     Postal code
         * @param description Property description
         * @param rent        Monthly rent
         * @param amenities   Available amenities
         * @param photos      Image path/URI
         * @param status      Availability status
         */
        public Dorm(String DormId, String city, String address, String zipcode, String description, String rent, String amenities, String photos, String status) {
            this.DormId = DormId;
            this.city = city;
            this.address = address;
            this.zipcode = zipcode;
            this.description = description;
            this.rent = rent;
            this.amenities = amenities;
            this.photos = photos;
            this.status = status;
        }
    }
}
