package remas.example.remasfinalproject.data.Dorm;

import androidx.room.Entity;
import androidx.room.PrimaryKey;
import java.io.Serializable;

/**
 * Entity class representing a Dormitory or Apartment listing in the Remas application.
 * This class is mapped to the "dorms" table in the Room database.
 * It implements Serializable to allow passing Dorms objects between Activities via Intents.
 */
@Entity(tableName = "dorms")
public class Dorms implements Serializable {

    /**
     * Unique identifier for each dorm listing. Auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    public long keyId;

    /**
     * The city where the dormitory is located.
     */
    public String city;

    /**
     * The full street address of the dormitory.
     */
    public String address;

    /**
     * The postal code for the dormitory location.
     */
    public String zipcode;

    /**
     * Detailed description of the property, including rules or specific features.
     */
    public String description;

    /**
     * The monthly cost of the dormitory as a String.
     */
    public String rent;

    /**
     * List of features (e.g., Wi-Fi, AC, Laundry) available in the property.
     */
    public String amenities;

    /**
     * URI or path string pointing to the property's image.
     */
    public String photos;

    /**
     * The current availability status (e.g., "Available", "Full", "Under Maintenance").
     */
    public String status;

    /**
     * Default constructor required by the Room persistence library.
     */
    public Dorms() {
    }

    /**
     * Returns the unique database key for this listing.
     * @return The primary key ID.
     */
    public long getKeyId() { return keyId; }

    /**
     * Sets the unique database key for this listing.
     * @param keyId The primary key ID to set.
     */
    public void setKeyId(long keyId) { this.keyId = keyId; }

    /**
     * @return The city name.
     */
    public String getCity() { return city; }

    /**
     * @param city The city name to set.
     */
    public void setCity(String city) { this.city = city; }

    /**
     * @return The property address.
     */
    public String getAddress() { return address; }

    /**
     * @param address The property address to set.
     */
    public void setAddress(String address) { this.address = address; }

    /**
     * @return The property zipcode.
     */
    public String getZipcode() { return zipcode; }

    /**
     * @param zipcode The property zipcode to set.
     */
    public void setZipcode(String zipcode) { this.zipcode = zipcode; }

    /**
     * @return The property description.
     */
    public String getDescription() { return description; }

    /**
     * @param description The property description to set.
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * @return The monthly rent value.
     */
    public String getRent() { return rent; }

    /**
     * @param rent The monthly rent value to set.
     */
    public void setRent(String rent) { this.rent = rent; }

    /**
     * @return The property amenities.
     */
    public String getAmenities() { return amenities; }

    /**
     * @param amenities The property amenities to set.
     */
    public void setAmenities(String amenities) { this.amenities = amenities; }

    /**
     * @return The photos path/URI.
     */
    public String getPhotos() { return photos; }

    /**
     * @param photos The photos path/URI to set.
     */
    public void setPhotos(String photos) { this.photos = photos; }

    /**
     * @return The property availability status.
     */
    public String getStatus() { return status; }

    /**
     * @param status The property availability status to set.
     */
    public void setStatus(String status) { this.status = status; }

    /**
     * Helper method to return a formatted string for debugging purposes.
     * @return A string representation of the Dorms object.
     */
    @Override
    public String toString() {
        return "Dorms{" +
                "keyId=" + keyId +
                ", city='" + city + '\'' +
                ", address='" + address + '\'' +
                ", rent='" + rent + '\'' +
                '}';
    }

    /**
     * Adapter Helper: Formats the rent price for display in the RecyclerView list.
     * @return The rent string prefixed with a currency symbol.
     */
    public String getPrice() {
        return rent != null ? "$" + rent : "$0";
    }

    /**
     * Adapter Helper: Provides the city name as the primary title for listing cards.
     * @return The city name or a default placeholder.
     */
    public String getTitle() {
        return city != null ? city : "Unknown Location";
    }

    /**
     * Adapter Helper: Maps amenities data to the 'Beds' display area in the UI layout.
     * @return The amenities string or N/A.
     */
    public String getBeds() {
        return amenities != null ? amenities : "N/A";
    }

    /**
     * Adapter Helper: Returns a static placeholder for bathroom info as this field is not in the DB yet.
     * @return A fixed bathroom count string.
     */
    public String getBaths() {
        return "1 Bath";
    }

    /**
     * Adapter Helper: Returns the property status as the 'Owner' or 'Availability' name.
     * @return The status string or a default placeholder.
     */
    public String getOwnerName() {
        return status != null ? status : "Available";
    }
}
